OnlineShop/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.ProductItems.GetProductItems());
        }
    }
}

OnlineShop/Areas/Admin/Controllers/PageItemController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;
using OnlineShop.Domain;
using OnlineShop.Domain.Entities;
using OnlineShop.Services;
using System.IO;
using System;


namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PageItemController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public PageItemController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.PageItems.GetPageItemByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(PageItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "assets/images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.PageItems.SavePageItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

OnlineShop/Areas/Admin/Controllers/ProductItemController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Domain;
using OnlineShop.Domain.Entities;
using OnlineShop.Services;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductItemController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ProductItemController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ProductItem() : dataManager.ProductItems.GetProductItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ProductItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "assets/images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.ProductItems.SaveProductItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ProductItems.DeleteProductItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

OnlineShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Domain;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            return View(dataManager.PageItems.GetPageItemByCodeWord("PageIndex"));
        }

        public IActionResult Contact()
        {
            return View(dataManager.PageItems.GetPageItemByCodeWord("PageContacts"));
        }
    }
}

OnlineShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Domain;
using System;
using System.Linq;
using OnlineShop.Models.ViewModels;
using OnlineShop.Domain.Entities;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly DataManager dataManager;

        public int PageSize = 4;

        public ProductController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id, int productPage = 1)
        {
            if (id != default)
            {
                return View("Show", dataManager.ProductItems.GetProductItemById(id));
            }
            
            ViewBag.TextField = dataManager.PageItems.GetPageItemByCodeWord("PageProduct");
            //return View(dataManager.ProductItems.GetProductItems());
            //Cart
            return View(new ProductsListViewModel { ProductItems = dataManager.ProductItems.GetProductItems()
                .OrderBy(p => p.Id)
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = dataManager.ProductItems.GetProductItems().Count()
                } });
        }
        //Cart
    
    }
}

OnlineShop/Areas/Admin/Views/Home/Index.cshtml
@using OnlineShop.Domain.Entities
@model IQueryable<ProductItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div class="module">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <div>
                    <h2>@strTitle</h2>
                    <div>
                        <h3>Наши услуги</h3>
                        <div class="div-box">
                            <a asp-area="Admin" asp-controller="ProductItem" asp-action="Edit" asp-route-id="">Добавить товар</a>
                        </div>
                        @if (Model.Any())
                        {
                            <div>
                                @foreach (ProductItem entity in Model)
                                {
                                    <div>
                                        <a asp-area="Admin" asp-controller="ProductItem" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                                        |
                                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ProductItem" asp-action="Delete" method="post">
                                            <input type="hidden" name="id" value="@entity.Id">
                                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                                        </form>
                                        |
                                        <a asp-area="" asp-controller="Product" asp-action="Index" asp-route-id="@entity.Id">
                                            @($"{entity.Title}")
                                        </a>
                                    </div>
                                }
                            </div>
                        }
                    </div>
                    <div class="div-box">
                        <h3>Редактировать страницы сайта</h3>
                        <a asp-area="Admin" asp-controller="PageItem" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
                        <a asp-area="Admin" asp-controller="PageItem" asp-action="Edit" asp-route-codeWord="PageServices">Наши товары</a>
                        <a asp-area="Admin" asp-controller="PageItem" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
                    </div>
                    <div class="div-box">
                        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
                            <input type="submit" value="Выйти" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>